In [6]:
import pandas as pd
import zipfile

zip_file = "IMDb Movies India.csv.zip"

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    print(zip_ref.namelist())

['IMDb Movies India.csv']

In [7]:
df = pd.read_csv("IMDb Movies India.csv.zip", encoding="latin1")

df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [8]:
# Dataset Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  str
 1   Year      14981 non-null  str
 2   Duration  7240 non-null   str
 3   Genre     13632 non-null  str
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   str
 6   Director  14984 non-null  str
 7   Actor 1   13892 non-null  str
 8   Actor 2   13125 non-null  str
 9   Actor 3   12365 non-null  str
dtypes: float64(1), str(9)
memory usage: 1.2 MB

In [9]:
# Dataset shape
print("Rows and Columns:", df.shape)

Rows and Columns: (15509, 10)

In [10]:
# Keep only rows where Rating is available
df = df.dropna(subset=['Rating'])

# Fill missing values in other columns
df['Genre'] = df['Genre'].fillna('Unknown')
df['Director'] = df['Director'].fillna('Unknown')
df['Actor 1'] = df['Actor 1'].fillna('Unknown')
df['Actor 2'] = df['Actor 2'].fillna('Unknown')
df['Actor 3'] = df['Actor 3'].fillna('Unknown')

print(df.shape)

(7919, 10)

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Genre'] = le.fit_transform(df['Genre'])
df['Director'] = le.fit_transform(df['Director'])
df['Actor 1'] = le.fit_transform(df['Actor 1'])
df['Actor 2'] = le.fit_transform(df['Actor 2'])
df['Actor 3'] = le.fit_transform(df['Actor 3'])

df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,268,7.0,8,811,1782,2815,377
3,#Yaaram,(2019),110 min,207,4.4,35,1749,1589,890,2572
5,...Aur Pyaar Ho Gaya,(1997),147 min,177,4.7,827,2005,508,85,2449
6,...Yahaan,(2005),142 min,331,7.4,"1,086",2643,931,1388,3030
8,?: A Question Mark,(2012),82 min,367,5.6,326,174,2521,1461,1205

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

X = df[['Genre','Director','Actor 1','Actor 2','Actor 3']]
y = df['Rating']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, pred))

R2 Score: 0.1138409253405096